import type { BaseBuilderData, SegmentPreset } from "@/types/editor";
import { baseFieldOptions } from "@/lib/editor-schema";

export const defaultBuilderData: BaseBuilderData = {
  audience: "Agencias de marketing",
  goal: "Encontrar novas empresas",
  segment: "Comercio e servicos",
  keyword: "",
  primaryCnae: "",
  secondaryCnaes: "",
  segmentNotes: "",
  state: "SP",
  city: "Campinas",
  region: "Campinas + região",
  district: "",
  cepStart: "",
  cepEnd: "",
  openedPeriod: "últimos 60 dias",
  customPeriod: "",
  companySize: ["ME", "EPP"],
  registrationStatus: "ativa",
  capitalRange: "sem preferencia",
  customCapital: "",
  branchType: "qualquer",
  baseFields: [...baseFieldOptions],
  extraFields: ["Telefone empresarial", "E-mail empresarial", "Site"],
  quantityRange: "101 a 500",
  deliveryFormat: "Excel",
  deliveryNotes: "",
  name: "",
  email: "",
  whatsapp: "",
  company: "",
  consent: false,
  companySite: "",
  source: "base-builder",
};

export const segmentPresets: SegmentPreset[] = [
  {
    id: "agencias",
    title: "Preset Agencias",
    description: "Empresas novas de comércio e serviços com potencial de presença digital.",
    audience: "Agencias de marketing",
    segment: "Comercio e servicos",
    goal: "Preparar campanha",
    openedPeriod: "últimos 90 dias",
    companySize: ["ME", "EPP"],
    cues: ["Empresas recém-abertas", "Região definida pelo usuário", "Interesse em presença digital"],
  },
  {
    id: "contabilidades",
    title: "Preset Contabilidades",
    description: "Empresas abertas recentemente, ME e EPP, em atividades de comercio e servicos.",
    audience: "Contabilidades",
    segment: "Comercio e servicos",
    goal: "Criar carteira comercial",
    openedPeriod: "últimos 90 dias",
    companySize: ["ME", "EPP"],
    cues: ["Empresas abertas recentemente", "ME e EPP", "Região definida pelo usuário"],
  },
  {
    id: "energia-solar",
    title: "Preset Energia Solar",
    description: "Empresas com consumo potencial em comercio, servicos, industrias leves e agro.",
    audience: "Energia solar",
    segment: "Comércio, serviços, indústrias leves e agronegócio",
    goal: "Abrir uma nova região",
    openedPeriod: "sem filtro de abertura",
    companySize: ["ME", "EPP", "Médio porte"],
    cues: ["Consumo potencial", "Região definida pelo usuário", "Atividades compatíveis"],
  },
  {
    id: "erp",
    title: "Preset ERP e Sistemas",
    description: "Empresas de comércio, distribuição, indústria e serviços com rotina operacional.",
    audience: "ERP e sistemas",
    segment: "Comércio, distribuição, indústria e serviços",
    goal: "Alimentar CRM",
    openedPeriod: "sem filtro de abertura",
    companySize: ["ME", "EPP"],
    cues: ["Porte ME/EPP", "CNAE definido pelo usuário", "Região definida pelo usuário"],
  },
];
