import type { BaseBuilderData, SegmentPreset } from "@/types/editor";
import { baseFieldOptions } from "@/lib/editor-schema";

export const defaultBuilderData: BaseBuilderData = {
  audience: "Agencias de marketing",
  goal: "Encontrar novas empresas",
  segment: "Comercio e servicos",
  keyword: "",
  primaryCnae: "",
  secondaryCnaes: "",
  segmentNotes: "",
  state: "SP",
  city: "Campinas",
  region: "Campinas + regiao",
  district: "",
  cepStart: "",
  cepEnd: "",
  openedPeriod: "ultimos 60 dias",
  customPeriod: "",
  companySize: ["ME", "EPP"],
  registrationStatus: "ativa",
  capitalRange: "sem preferencia",
  customCapital: "",
  branchType: "qualquer",
  baseFields: [...baseFieldOptions],
  extraFields: ["Telefone empresarial", "E-mail empresarial", "Site"],
  quantityRange: "101 a 500",
  deliveryFormat: "Excel",
  deliveryNotes: "",
  name: "",
  email: "",
  whatsapp: "",
  company: "",
  consent: false,
  companySite: "",
  source: "base-builder",
};

export const segmentPresets: SegmentPreset[] = [
  {
    id: "agencias",
    title: "Preset Agencias",
    description: "Empresas novas de comercio e servicos com potencial de presenca digital.",
    audience: "Agencias de marketing",
    segment: "Comercio e servicos",
    goal: "Preparar campanha",
    openedPeriod: "ultimos 90 dias",
    companySize: ["ME", "EPP"],
    cues: ["Empresas recem-abertas", "Regiao definida pelo usuario", "Interesse em presenca digital"],
  },
  {
    id: "contabilidades",
    title: "Preset Contabilidades",
    description: "Empresas abertas recentemente, ME e EPP, em atividades de comercio e servicos.",
    audience: "Contabilidades",
    segment: "Comercio e servicos",
    goal: "Criar carteira comercial",
    openedPeriod: "ultimos 90 dias",
    companySize: ["ME", "EPP"],
    cues: ["Empresas abertas recentemente", "ME e EPP", "Regiao definida pelo usuario"],
  },
  {
    id: "energia-solar",
    title: "Preset Energia Solar",
    description: "Empresas com consumo potencial em comercio, servicos, industrias leves e agro.",
    audience: "Energia solar",
    segment: "Comercio, servicos, industrias leves e agronegocio",
    goal: "Abrir uma nova regiao",
    openedPeriod: "sem filtro de abertura",
    companySize: ["ME", "EPP", "Medio porte"],
    cues: ["Consumo potencial", "Regiao definida pelo usuario", "Atividades compativeis"],
  },
  {
    id: "erp",
    title: "Preset ERP e Sistemas",
    description: "Empresas de comercio, distribuicao, industria e servicos com rotina operacional.",
    audience: "ERP e sistemas",
    segment: "Comercio, distribuicao, industria e servicos",
    goal: "Alimentar CRM",
    openedPeriod: "sem filtro de abertura",
    companySize: ["ME", "EPP"],
    cues: ["Porte ME/EPP", "CNAE definido pelo usuario", "Regiao definida pelo usuario"],
  },
];
