export const routes = {
  home: "/",
  products: "/produtos",
  productRecentlyOpened: "/produtos/empresas-recem-abertas",
  productAgencies: "/produtos/agencias-marketing",
  productAccounting: "/produtos/contabilidades",
  productCustom: "/produtos/base-personalizada",
  productSample: "/produtos/amostra-gratuita",
  builder: "/montar-minha-base",
  audiences: "/para-quem-e",
  howItWorks: "/como-funciona",
  baseFields: "/campos-da-base",
  faq: "/faq",
  contact: "/contato",
  about: "/sobre",
  privacy: "/politica-de-privacidade",
  suppression: "/politica-de-supressao",
  cookies: "/politica-de-cookies",
  terms: "/termos-de-uso",
  checkoutSuccess: "/compra/sucesso",
  checkoutPending: "/compra/pendente",
  checkoutError: "/compra/erro",
  order: "/pedido/[id]",
  admin: "/admin",
} as const;

export const publicRoutes = [
  routes.home,
  routes.products,
  routes.productRecentlyOpened,
  routes.productAgencies,
  routes.productAccounting,
  routes.productCustom,
  routes.productSample,
  routes.builder,
  routes.audiences,
  routes.howItWorks,
  routes.baseFields,
  routes.faq,
  routes.contact,
  routes.about,
  routes.privacy,
  routes.suppression,
  routes.cookies,
  routes.terms,
  routes.checkoutSuccess,
  routes.checkoutPending,
  routes.checkoutError,
];

export const legacyRedirects = ["/blog", "/conteudos", "/solucoes", "/insights"];
